#!/usr/bin/env node
import { build } from 'esbuild';

/**
 * Bundles the Action entry point into `dist/index.js`, which is committed.
 *
 * A `node24` action runs the file `action.yml` points at, in a checkout that has
 * no `node_modules` — so either the dependencies are vendored or the entry point
 * is bundled. Bundling wins: one file to review, one file in the diff, and a
 * consumer's runner executes nothing that was not in the pull request.
 *
 * `pnpm build:check` re-runs this into a temporary file and compares, so a
 * `dist/` that drifts from `src/` fails CI rather than shipping.
 */
const options = {
  entryPoints: ['src/action-entry.ts'],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  legalComments: 'inline',
  banner: {
    js: '// Generated by `pnpm build` from src/. Do not edit — edit the source and rebuild.'
  }
};

const outfile = process.argv[2] ?? 'dist/index.js';

await build({ ...options, outfile });
process.stdout.write(`Bundled ${options.entryPoints[0]} → ${outfile}\n`);
